# Generated by Django 5.2.7 on 2026-09-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_category_alter_listing_image_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='start_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
