# Generated by Django 5.2.7 on 2026-09-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_src',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
